use super::{BindingRow, DeclarationKind, Role, RoleSet, Ruling, Visibility};
use crate::languages::Language;

pub(super) static ROWS: &[BindingRow] = &[
    BindingRow {
        language: Language::Go,
        kind: "block",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-go-block",
    },
    BindingRow {
        language: Language::Go,
        kind: "switch_statement",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-go-switch_statement",
    },
    // spec §6.1 line 113: Header visibility deferred to E1b (lossless port)
    BindingRow {
        language: Language::Go,
        kind: "if_statement",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-go-if_statement",
    },
    BindingRow {
        language: Language::Go,
        kind: "for_statement",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-go-for_statement",
    },
    BindingRow {
        language: Language::Go,
        kind: "expression_switch_statement",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-go-expression_switch_statement",
    },
    BindingRow {
        language: Language::Go,
        kind: "type_switch_statement",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-go-type_switch_statement",
    },
    BindingRow {
        language: Language::Go,
        kind: "select_statement",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-go-select_statement",
    },
    BindingRow {
        language: Language::Go,
        kind: "short_var_declaration",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &[],
        declaration: Some(DeclarationKind::GoShort),
        visibility: Visibility::AfterIntroduction,
        ruling: Ruling::Classified,
        regression: "e0a-go-short_var_declaration",
    },
    BindingRow {
        language: Language::Go,
        kind: "var_declaration",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &[],
        declaration: Some(DeclarationKind::Other),
        visibility: Visibility::AfterIntroduction,
        ruling: Ruling::Classified,
        regression: "e0a-go-var_declaration",
    },
    BindingRow {
        language: Language::Go,
        kind: "const_declaration",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &[],
        declaration: Some(DeclarationKind::Other),
        visibility: Visibility::AfterIntroduction,
        ruling: Ruling::Classified,
        regression: "e0a-go-const_declaration",
    },
    BindingRow {
        language: Language::Go,
        kind: "parameter_list",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &[],
        declaration: Some(DeclarationKind::Parameter),
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-x-go-parameter_list",
    },
];
