use super::{BindingRow, DeclarationKind, Predicate, Role, RoleSet, Ruling, Visibility};
use crate::languages::Language;

pub(super) static ROWS: &[BindingRow] = &[
    BindingRow {
        language: Language::JavaScript,
        kind: "statement_block",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-js-statement_block",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "class_body",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-js-class_body",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "function_declaration",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-js-function_declaration",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "function_expression",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-js-function_expression",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "arrow_function",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-js-arrow_function",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "for_statement",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-js-for_statement",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "for_in_statement",
        variant: Some(Predicate::FieldTextIs {
            field: "kind",
            any_of: &["let", "const"],
        }),
        roles: RoleSet::of(&[Role::Scope, Role::Binding]),
        fields: &["left"],
        declaration: Some(DeclarationKind::Other),
        visibility: Visibility::Header,
        ruling: Ruling::Classified,
        regression: "e0a-js-for_in_statement",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "for_in_statement",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-js-for_in_statement",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "variable_declaration",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &[],
        declaration: Some(DeclarationKind::JavaScriptVar),
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-js-variable_declaration",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "lexical_declaration",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &[],
        declaration: Some(DeclarationKind::Other),
        visibility: Visibility::AfterIntroduction,
        ruling: Ruling::Classified,
        regression: "e0a-js-lexical_declaration",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "class_declaration",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &["name"],
        declaration: Some(DeclarationKind::Other),
        visibility: Visibility::AfterIntroduction,
        ruling: Ruling::Classified,
        regression: "e0a-js-class_declaration",
    },
    BindingRow {
        language: Language::JavaScript,
        kind: "formal_parameters",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &[],
        declaration: Some(DeclarationKind::Parameter),
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-x-js-formal_parameters",
    },
];
