use super::{BindingRow, DeclarationKind, Role, RoleSet, Ruling, Visibility};
use crate::languages::Language;

pub(super) static ROWS: &[BindingRow] = &[
    BindingRow {
        language: Language::Python,
        kind: "function_definition",
        variant: None,
        roles: RoleSet::of(&[Role::Scope, Role::Binding]),
        fields: &["name"],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-py-function_definition",
    },
    BindingRow {
        language: Language::Python,
        kind: "lambda",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-py-lambda",
    },
    BindingRow {
        language: Language::Python,
        kind: "class_definition",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-py-class_definition",
    },
    BindingRow {
        language: Language::Python,
        kind: "list_comprehension",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-py-list_comprehension",
    },
    BindingRow {
        language: Language::Python,
        kind: "set_comprehension",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-py-set_comprehension",
    },
    BindingRow {
        language: Language::Python,
        kind: "dictionary_comprehension",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-py-dictionary_comprehension",
    },
    BindingRow {
        language: Language::Python,
        kind: "generator_expression",
        variant: None,
        roles: RoleSet::of(&[Role::Scope]),
        fields: &[],
        declaration: None,
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-py-generator_expression",
    },
    BindingRow {
        language: Language::Python,
        kind: "assignment",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &["left"],
        declaration: Some(DeclarationKind::PythonAssignment),
        visibility: Visibility::AfterIntroduction,
        ruling: Ruling::Classified,
        regression: "e0a-py-assignment",
    },
    BindingRow {
        language: Language::Python,
        kind: "augmented_assignment",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &["left"],
        declaration: Some(DeclarationKind::PythonAssignment),
        visibility: Visibility::AfterIntroduction,
        ruling: Ruling::Classified,
        regression: "e0a-py-augmented_assignment",
    },
    BindingRow {
        language: Language::Python,
        kind: "named_expression",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &["left"],
        declaration: Some(DeclarationKind::PythonAssignment),
        visibility: Visibility::AfterIntroduction,
        ruling: Ruling::Classified,
        regression: "e0a-py-named_expression",
    },
    BindingRow {
        language: Language::Python,
        kind: "parameters",
        variant: None,
        roles: RoleSet::of(&[Role::Binding]),
        fields: &[],
        declaration: Some(DeclarationKind::Parameter),
        visibility: Visibility::WholeScope,
        ruling: Ruling::Classified,
        regression: "e0a-x-py-parameters",
    },
];
