macro_rules! placeholder_owners {
    ($language:ident, $predicate:ident) => {
        &[
            (($language::Python, "assignment", None::<$predicate>, "e0a-py-assignment"), "Task 11"),
            (($language::Python, "augmented_assignment", None::<$predicate>, "e0a-py-augmented_assignment"), "Task 11"),
            (($language::Python, "named_expression", None::<$predicate>, "e0a-py-named_expression"), "Task 11"),
            (($language::Python, "function_definition", None::<$predicate>, "e0a-py-function_definition"), "Task 12"),
            (($language::Python, "lambda", None::<$predicate>, "e0a-py-lambda"), "Task 12"),
            (($language::Python, "class_definition", None::<$predicate>, "e0a-py-class_definition"), "Task 12"),
            (($language::Python, "list_comprehension", None::<$predicate>, "e0a-py-list_comprehension"), "Task 12"),
            (($language::Python, "set_comprehension", None::<$predicate>, "e0a-py-set_comprehension"), "Task 12"),
            (($language::Python, "dictionary_comprehension", None::<$predicate>, "e0a-py-dictionary_comprehension"), "Task 12"),
            (($language::Python, "generator_expression", None::<$predicate>, "e0a-py-generator_expression"), "Task 12"),
            (($language::Python, "parameters", None::<$predicate>, "e0a-x-py-parameters"), "Task 12"),
            (($language::JavaScript, "arrow_function", None::<$predicate>, "e0a-js-arrow_function"), "Task 16"),
            (($language::JavaScript, "class_body", None::<$predicate>, "e0a-js-class_body"), "Task 16"),
            (($language::JavaScript, "class_declaration", None::<$predicate>, "e0a-js-class_declaration"), "Task 16"),
            (($language::JavaScript, "for_statement", None::<$predicate>, "e0a-js-for_statement"), "Task 16"),
            (($language::JavaScript, "formal_parameters", None::<$predicate>, "e0a-x-js-formal_parameters"), "Task 16"),
            (($language::JavaScript, "function_declaration", None::<$predicate>, "e0a-js-function_declaration"), "Task 16"),
            (($language::JavaScript, "function_expression", None::<$predicate>, "e0a-js-function_expression"), "Task 16"),
            (($language::JavaScript, "statement_block", None::<$predicate>, "e0a-js-statement_block"), "Task 16"),
            (($language::JavaScript, "variable_declaration", None::<$predicate>, "e0a-js-variable_declaration"), "Task 16"),
            (($language::TypeScript, "arrow_function", None::<$predicate>, "e0a-js-arrow_function"), "Task 17"),
            (($language::TypeScript, "class_body", None::<$predicate>, "e0a-js-class_body"), "Task 17"),
            (($language::TypeScript, "class_declaration", None::<$predicate>, "e0a-js-class_declaration"), "Task 17"),
            (($language::TypeScript, "for_statement", None::<$predicate>, "e0a-js-for_statement"), "Task 17"),
            (($language::TypeScript, "formal_parameters", None::<$predicate>, "e0a-x-js-formal_parameters"), "Task 17"),
            (($language::TypeScript, "function_declaration", None::<$predicate>, "e0a-js-function_declaration"), "Task 17"),
            (($language::TypeScript, "function_expression", None::<$predicate>, "e0a-js-function_expression"), "Task 17"),
            (($language::TypeScript, "lexical_declaration", None::<$predicate>, "e0a-js-lexical_declaration"), "Task 17"),
            (($language::TypeScript, "statement_block", None::<$predicate>, "e0a-js-statement_block"), "Task 17"),
            (($language::TypeScript, "variable_declaration", None::<$predicate>, "e0a-js-variable_declaration"), "Task 17"),
            (($language::Tsx, "arrow_function", None::<$predicate>, "e0a-js-arrow_function"), "Task 18"),
            (($language::Tsx, "class_body", None::<$predicate>, "e0a-js-class_body"), "Task 18"),
            (($language::Tsx, "class_declaration", None::<$predicate>, "e0a-js-class_declaration"), "Task 18"),
            (($language::Tsx, "for_statement", None::<$predicate>, "e0a-js-for_statement"), "Task 18"),
            (($language::Tsx, "formal_parameters", None::<$predicate>, "e0a-x-js-formal_parameters"), "Task 18"),
            (($language::Tsx, "function_declaration", None::<$predicate>, "e0a-js-function_declaration"), "Task 18"),
            (($language::Tsx, "function_expression", None::<$predicate>, "e0a-js-function_expression"), "Task 18"),
            (($language::Tsx, "lexical_declaration", None::<$predicate>, "e0a-js-lexical_declaration"), "Task 18"),
            (($language::Tsx, "statement_block", None::<$predicate>, "e0a-js-statement_block"), "Task 18"),
            (($language::Tsx, "variable_declaration", None::<$predicate>, "e0a-js-variable_declaration"), "Task 18"),
            (($language::Go, "block", None::<$predicate>, "e0a-go-block"), "Task 13"),
            (($language::Go, "const_declaration", None::<$predicate>, "e0a-go-const_declaration"), "Task 13"),
            (($language::Go, "expression_switch_statement", None::<$predicate>, "e0a-go-expression_switch_statement"), "Task 13"),
            (($language::Go, "for_statement", None::<$predicate>, "e0a-go-for_statement"), "Task 13"),
            (($language::Go, "if_statement", None::<$predicate>, "e0a-go-if_statement"), "Task 13"),
            (($language::Go, "parameter_list", None::<$predicate>, "e0a-x-go-parameter_list"), "Task 13"),
            (($language::Go, "select_statement", None::<$predicate>, "e0a-go-select_statement"), "Task 13"),
            (($language::Go, "short_var_declaration", None::<$predicate>, "e0a-go-short_var_declaration"), "Task 13"),
            (($language::Go, "type_switch_statement", None::<$predicate>, "e0a-go-type_switch_statement"), "Task 13"),
            (($language::Go, "var_declaration", None::<$predicate>, "e0a-go-var_declaration"), "Task 13"),
            (($language::Java, "formal_parameters", None::<$predicate>, "e0a-x-java-formal_parameters"), "Task 20"),
            (($language::Java, "spread_parameter", None::<$predicate>, "e0a-x-java-spread_parameter"), "Task 20"),
            (($language::C, "parameter_declaration", None::<$predicate>, "e0a-x-c-parameter_declaration"), "Task 22"),
            (($language::C, "parameter_list", None::<$predicate>, "e0a-x-c-parameter_list"), "Task 22"),
            (($language::Cpp, "parameter_declaration", None::<$predicate>, "e0a-x-cpp-parameter_declaration"), "Task 23"),
            (($language::Cpp, "parameter_list", None::<$predicate>, "e0a-x-cpp-parameter_list"), "Task 23"),
            (($language::Rust, "block", None::<$predicate>, "e0a-rs-block"), "Task 14"),
            (($language::Rust, "const_item", None::<$predicate>, "e0a-rs-const_item"), "Task 14"),
            (($language::Rust, "let_declaration", None::<$predicate>, "e0a-rs-let_declaration"), "Task 14"),
            (($language::Rust, "parameters", None::<$predicate>, "e0a-x-rs-parameters"), "Task 14"),
            (($language::Rust, "static_item", None::<$predicate>, "e0a-rs-static_item"), "Task 14"),
            (($language::Lua, "parameters", None::<$predicate>, "e0a-x-lua-parameters"), "Task 26"),
        ]
    };
}
