import { createHash, randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import { existsSync, linkSync, lstatSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const REQUEST = "prism.native-parameter-request/1";
export const OUTPUT = "prism.native-parameter-characterization/1";
export const LIMITS = Object.freeze({ files: 16, sites: 16, sourceBytes: 256 * 1024, inputBytes: 2 * 1024 * 1024, outputBytes: 4 * 1024 * 1024, wallMs: 15_000 });
const MANIFEST = ["schema", "upstream_repository", "upstream_commit", "upstream_tree", "parent_packet_sha256", "parent_manifest_sha256", "selection", "member_count", "source_bytes", "site_count", "members", "sites"];
const MEMBER = ["path", "sha256", "bytes", "script_kind", "declaration_only", "test_path"];
const SITE = ["path", "start_byte", "end_byte", "compiler_kind", "object_ordinals", "later_required_ordinals"];
const sha = value => createHash("sha256").update(value).digest("hex");
function compare(left, right) { const a = [...left]; const b = [...right]; for (let index = 0; index < Math.min(a.length, b.length); index += 1) { const difference = a[index].codePointAt(0) - b[index].codePointAt(0); if (difference) return difference; } return a.length - b.length; }
const hex = value => typeof value === "string" && /^[0-9a-f]{64}$/.test(value);
const integer = value => Number.isSafeInteger(value) && value >= 0;
const fail = message => { throw Error(message); };
function exact(value, keys, label) { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== keys.length || !keys.every(key => Object.hasOwn(value, key))) fail(`invalid ${label}`); return value; }
function utf8(bytes, label) { try { return new TextDecoder("utf-8", { fatal: true, ignoreBOM: true }).decode(bytes); } catch { fail(`invalid UTF-8: ${label}`); } }
function safePath(value) { return typeof value === "string" && value && !value.startsWith("/") && !value.includes("\\") && !/[\0-\x1f]/.test(value) && value.split("/").every(part => part && part !== "." && part !== ".."); }
function ordinals(value) { if (!Array.isArray(value) || value.some((item, index) => !integer(item) || index && value[index - 1] >= item)) fail("invalid ordinal array"); return value; }
function boundaries(text) { const result = new Set([0]); let offset = 0; for (const point of text) { offset += Buffer.byteLength(point); result.add(offset); } return result; }
function limits(overrides = {}) { exact(overrides, Object.keys(overrides), "limit overrides"); if (Object.keys(overrides).some(key => !Object.hasOwn(LIMITS, key))) fail("invalid limits"); const result = { ...LIMITS, ...overrides }; if (Object.entries(result).some(([key, value]) => !integer(value) || value > LIMITS[key])) fail("invalid limits"); return result; }
function mapping(file, kind) { const extension = path.posix.extname(file); const expected = { ".js": ["JavaScript", "JavaScript"], ".jsx": ["Jsx", "JavaScript"], ".ts": ["TypeScript", "TypeScript"], ".tsx": ["Tsx", "Tsx"] }[extension]; if (!expected || expected[0] !== kind) fail("script kind/path mismatch"); return expected[1]; }
function checked(root, relative) { let current = root; const rootStat = lstatSync(current); if (!rootStat.isDirectory() || rootStat.isSymbolicLink()) fail("source root is not a regular directory"); for (const part of relative.split("/")) { current = path.join(current, part); const stat = lstatSync(current); if (stat.isSymbolicLink()) fail(`symlink in selected path: ${relative}`); } return current; }
function fileBytes(root, relative) { const target = checked(root, relative); const stat = lstatSync(target); if (!stat.isFile() || stat.isSymbolicLink()) fail(`member is not a regular file: ${relative}`); return readFileSync(target); }
function binaryBytes(native) { const stat = lstatSync(native); if (!stat.isFile() || stat.isSymbolicLink()) fail("native binary is not a regular file"); return readFileSync(native); }

export function prepare(options, overrides) {
  const cap = limits(overrides); const root = path.resolve(options.root); const manifestBytes = readFileSync(options.manifest); const manifestSha = sha(manifestBytes);
  if (!hex(options.manifestSha256) || manifestSha !== options.manifestSha256) fail("manifest SHA mismatch");
  const manifest = exact(JSON.parse(utf8(manifestBytes, "manifest")), MANIFEST, "manifest");
  if (manifest.schema !== "prism.native-parameter-sites/1") fail("unsupported manifest schema");
  for (const key of ["upstream_repository", "upstream_commit", "upstream_tree", "selection"]) if (typeof manifest[key] !== "string" || !manifest[key]) fail(`invalid manifest ${key}`);
  if (!hex(manifest.parent_packet_sha256) || !hex(manifest.parent_manifest_sha256) || !integer(manifest.member_count) || !integer(manifest.source_bytes) || !integer(manifest.site_count) || !Array.isArray(manifest.members) || !Array.isArray(manifest.sites)) fail("invalid manifest scalar");
  if (!manifest.members.length || manifest.members.length !== manifest.member_count || manifest.members.length > cap.files || manifest.sites.length !== manifest.site_count || manifest.sites.length > cap.sites) fail("manifest count limit");
  const members = new Map(); let sourceBytes = 0;
  for (const member of manifest.members) { exact(member, MEMBER, "member"); if (!safePath(member.path) || !hex(member.sha256) || !integer(member.bytes) || typeof member.script_kind !== "string" || typeof member.declaration_only !== "boolean" || typeof member.test_path !== "boolean" || members.has(member.path)) fail("invalid or duplicate member"); mapping(member.path, member.script_kind); members.set(member.path, member); sourceBytes += member.bytes; }
  if (sourceBytes !== manifest.source_bytes || sourceBytes > cap.sourceBytes) fail("manifest source byte limit");
  const grouped = new Map(); const selectors = new Set();
  for (const site of manifest.sites) { exact(site, SITE, "site"); const tuple = `${site.path}\0${site.start_byte}\0${site.end_byte}`; if (!members.has(site.path) || !integer(site.start_byte) || !integer(site.end_byte) || site.start_byte >= site.end_byte || !["FunctionDeclaration", "FunctionExpression", "ArrowFunction"].includes(site.compiler_kind) || selectors.has(tuple)) fail("invalid or duplicate selector"); selectors.add(tuple); ordinals(site.object_ordinals); ordinals(site.later_required_ordinals); (grouped.get(site.path) ?? grouped.set(site.path, []).get(site.path)).push(site); }
  if (grouped.size !== members.size) fail("unreferenced member");
  const files = [];
  for (const member of [...members.values()].sort((left, right) => compare(left.path, right.path))) { const bytes = fileBytes(root, member.path); if (bytes.length !== member.bytes || sha(bytes) !== member.sha256) fail(`member identity mismatch: ${member.path}`); const source = utf8(bytes, member.path); const sites = grouped.get(member.path).sort((left, right) => left.start_byte - right.start_byte || left.end_byte - right.end_byte); const valid = boundaries(source); if (sites.some(site => site.end_byte > bytes.length || !valid.has(site.start_byte) || !valid.has(site.end_byte))) fail("invalid selector boundary"); files.push({ path: member.path, sha256: member.sha256, bytes: member.bytes, script_kind: member.script_kind, source, sites }); }
  const native = path.resolve(options.native); const nativeBytes = binaryBytes(native); if (!hex(options.nativeSha256) || sha(nativeBytes) !== options.nativeSha256) fail("native binary SHA mismatch");
  const request = { schema: REQUEST, input_manifest_sha256: manifestSha, native_binary_sha256: options.nativeSha256, files };
  if (Buffer.byteLength(`${JSON.stringify(request)}\n`) > cap.inputBytes) fail("worker input limit"); return { request, native, cap };
}

function occurrence(value) { exact(value, ["name", "start_byte", "end_byte", "source_ordinal"], "occurrence"); if (typeof value.name !== "string" || !integer(value.start_byte) || !integer(value.end_byte) || !(value.source_ordinal === null || integer(value.source_ordinal))) fail("invalid occurrence"); }
function response(value, request) {
  exact(value, ["schema", "measurement", "authorizes_runtime_edge", "native_entry_measured", "callee_resolution_measured", "input_manifest_sha256", "native_binary_sha256", "files", "sites", "totals", "next_action", "reason"], "output");
  if (value.schema !== OUTPUT || value.measurement !== "native_parameter_api_characterization" || value.authorizes_runtime_edge || value.native_entry_measured || value.callee_resolution_measured || value.input_manifest_sha256 !== request.input_manifest_sha256 || value.native_binary_sha256 !== request.native_binary_sha256 || !Array.isArray(value.files) || !Array.isArray(value.sites)) fail("invalid output schema");
  const expectedFiles = [...request.files].sort((left, right) => compare(left.path, right.path)); const expectedSites = expectedFiles.flatMap(file => file.sites).sort((left, right) => compare(left.path, right.path) || left.start_byte - right.start_byte || left.end_byte - right.end_byte);
  if (value.files.length !== expectedFiles.length || value.sites.length !== expectedSites.length) fail("output identity mismatch");
  value.files.forEach((file, index) => { exact(file, ["path", "sha256", "bytes", "language", "parse_error_count"], "output file"); const expected = expectedFiles[index]; if (file.path !== expected.path || file.sha256 !== expected.sha256 || file.bytes !== expected.bytes || file.language !== mapping(expected.path, expected.script_kind) || !integer(file.parse_error_count)) fail("output file identity mismatch"); });
  const statuses = new Set(["unique_named", "unique_unnamed", "missing", "ambiguous", "recovery_quarantined"]); const eligible = new Set(["not_clean_named", "native_slot_authority_unavailable", "selection_native_shape_mismatch", "eligible", "no_selected_suffix_binding_gap"]);
  value.sites.forEach((site, index) => { exact(site, ["path", "start_byte", "end_byte", "status", "candidates", "next_proof_eligibility"], "output site"); const expected = expectedSites[index]; if (site.path !== expected.path || site.start_byte !== expected.start_byte || site.end_byte !== expected.end_byte || !statuses.has(site.status) || !eligible.has(site.next_proof_eligibility) || !Array.isArray(site.candidates)) fail("output site identity mismatch"); for (const candidate of site.candidates) { exact(candidate, ["kind", "start_line", "end_line", "name", "parameters", "slots", "bindings"], "candidate"); if (!integer(candidate.start_line) || !integer(candidate.end_line) || !(candidate.name === null || typeof candidate.name === "string") || !Array.isArray(candidate.parameters) || !(candidate.slots === null || Array.isArray(candidate.slots)) || !Array.isArray(candidate.bindings)) fail("invalid candidate"); for (const parameter of candidate.parameters) { exact(parameter, ["ordinal", "kind", "start_byte", "end_byte", "pattern_kind", "ordinary_required_identifier"], "parameter"); if (!integer(parameter.ordinal) || typeof parameter.kind !== "string" || !integer(parameter.start_byte) || !integer(parameter.end_byte) || typeof parameter.pattern_kind !== "string" || typeof parameter.ordinary_required_identifier !== "boolean") fail("invalid parameter"); } candidate.slots?.forEach(occurrence); candidate.bindings.forEach(occurrence); } });
  exact(value.totals, ["files", "sites", "unique_named", "unique_unnamed", "missing", "ambiguous", "recovery_quarantined"], "totals"); const total = Object.values(value.totals); if (total.some(item => !integer(item)) || value.totals.files !== value.files.length || value.totals.sites !== value.sites.length || total.slice(2).reduce((sum, item) => sum + item, 0) !== value.sites.length || [...statuses].some(status => value.totals[status] !== value.sites.filter(site => site.status === status).length)) fail("invalid totals");
  const any = value.sites.some(site => site.next_proof_eligibility === "eligible"); if (value.next_action !== (any ? "bounded_entry_and_call_proof" : "defer") || value.reason !== (any ? "named_native_binding_outside_legacy_prefix_requires_entry_and_call_proof" : "no_eligible_native_slot_gap")) fail("invalid next action"); return value;
}
export function runNative(native, request, cap = LIMITS, args = []) { const result = spawnSync(native, args, { input: `${JSON.stringify(request)}\n`, timeout: cap.wallMs, maxBuffer: cap.outputBytes }); if (result.error?.code === "ETIMEDOUT" || result.signal) fail("worker timeout"); if (result.error || result.status !== 0) fail(`worker failed: ${Buffer.from(result.stderr ?? []).toString("utf8")}`); const bytes = Buffer.from(result.stdout ?? []); if (bytes.length > cap.outputBytes) fail("worker output limit"); const output = utf8(bytes, "worker output"); const value = JSON.parse(output); if (output !== `${JSON.stringify(value)}\n`) fail("noncanonical worker output"); response(value, request); return output; }
function publish(out, output) { const target = path.resolve(out); if (existsSync(target)) fail("output already exists"); const stage = path.join(path.dirname(target), `.${path.basename(target)}.partial-${randomUUID()}`); try { writeFileSync(stage, output, { flag: "wx" }); linkSync(stage, target); } finally { if (existsSync(stage)) unlinkSync(stage); } }
export function launch(options, overrides) { const ready = prepare(options, overrides); const output = runNative(ready.native, ready.request, ready.cap); publish(options.out, output); return JSON.parse(output); }
function cli(argv) { const names = new Map([["--root", "root"], ["--manifest", "manifest"], ["--manifest-sha256", "manifestSha256"], ["--native", "native"], ["--native-sha256", "nativeSha256"], ["--out", "out"]]); const options = {}; for (let index = 0; index < argv.length; index += 2) { const key = names.get(argv[index]); if (!key || !argv[index + 1] || Object.hasOwn(options, key)) fail("unknown, missing, or duplicate flag"); options[key] = argv[index + 1]; } if (argv.length !== names.size * 2 || Object.keys(options).length !== names.size) fail("all flags are required"); return options; }
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) { try { launch(cli(process.argv.slice(2))); } catch (error) { process.stderr.write(`${error.message}\n`); process.exitCode = 1; } }
