import test from 'node:test';
import assert from 'node:assert/strict';
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const script = fileURLToPath(new URL('./verify-typescript-grammar.mjs', import.meta.url));
const supported = process.platform === 'darwin' && process.arch === 'arm64' && process.version === 'v26.0.0';
const archives = process.env.PRISM_GRAMMAR_ARCHIVES;
const hostSkip = supported ? false : 'bootstrap verifier pins Node26.0.0/macOS arm64; normal Cargo builds do not require it';
function run(file, args) {
  return spawnSync(process.execPath, [file, ...args], { encoding: 'utf8', timeout: 180_000, maxBuffer: 8 * 1024 * 1024 });
}

test('verifier requires an explicit archive directory or download choice', () => {
  const result = run(script, []);
  assert.equal(result.error, undefined);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /usage: node scripts\/verify-typescript-grammar/);
});

test('corrupted upstream archive refuses before unpacking or executing the generator', { skip: hostSkip }, () => {
  const input = mkdtempSync(join(tmpdir(), 'prism-grammar-bad-input-'));
  writeFileSync(join(input, 'upstream.tar.gz'), 'not the pinned archive');
  const result = run(script, [input]);
  assert.equal(result.error, undefined);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /archive pin: upstream\.tar\.gz/);
  const scratch = result.stdout.match(/Evidence directory \(retained\): (.+)/)?.[1];
  assert(scratch);
  assert(!existsSync(join(scratch, 'tree-sitter')));
  assert(!existsSync(join(scratch, 'tree-sitter-typescript-f975a621f4e7f532fe322e13c4f79495e0a7b2e7')));
});

test('valid inputs cannot authenticate tampered shipped generated bytes', {
  skip: hostSkip || (!archives && 'set PRISM_GRAMMAR_ARCHIVES to the already acquired pinned archives; this test never downloads'),
}, () => {
  const fixture = mkdtempSync(join(tmpdir(), 'prism-grammar-bad-output-'));
  mkdirSync(join(fixture, 'scripts'));
  cpSync(script, join(fixture, 'scripts/verify-typescript-grammar.mjs'));
  cpSync(resolve(dirname(script), '../vendor'), join(fixture, 'vendor'), { recursive: true });
  const parser = join(fixture, 'vendor/tree-sitter-typescript/typescript/src/parser.c');
  const changed = Buffer.concat([readFileSync(parser), Buffer.from('\n/* tampered output */\n')]);
  writeFileSync(parser, changed);
  const result = run(join(fixture, 'scripts/verify-typescript-grammar.mjs'), [archives]);
  assert.equal(result.error, undefined);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /typescript: shipped generated bytes differ/);
  assert.deepEqual(readFileSync(parser), changed, 'verification must not repair or overwrite its input');
});
